name: Robot Framework Reporter

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test-auto:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox geckodriver
        pip install robotframework

    - name: Run Robot Framework Tests
      uses: joonvena/robotframework-docker-action@v1.0
      with:
        robot_tests_dir: tests
        robot_options: "--outputdir tests/output" # Ensures test reports are saved in the correct directory

    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports
        path: STV3_TEST/output

  report:
    if: always()
    needs: [test-auto]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Test Reports
      uses: actions/download-artifact@v4
      with:
        name: test-reports
        path: STV3_TEST/output

    - name: Generate Report
      uses: joonvena/robotframework-reporter-action@v2
      with:
        gh_access_token: ${{ secrets.GITHUB_TOKEN }}
        output_path: tests/output/report.html # Explicit path for the final report output
